[package]
name = "boomer"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
byteorder = "^1.3"
clap = "^2.33"
image = "^0.23"
log = "^0.4"
nucleid = { git = "https://github.com/mripard/nucleid.git" }
twox-hash = "^1.5"
